version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: group-bot

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/group-bot
    depends_on:
      - mongo
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo-data: 