// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syqylihnpygqvqpitoco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5cXlsaWhucHlncXZxcGl0b2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTMyNDIsImV4cCI6MjA2NzA2OTI0Mn0.fAzXK42YpHaEEqUySsDkU1Cz8sqJ9VGcEZFLc0x4eaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});